import React, { useState, useCallback } from 'react';
import { View, Text, StyleSheet, ScrollView, Alert, TouchableOpacity } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { getReportByIdApi, deleteReportApi } from '../../api/reportApi';
import LoadingSpinner from '../../components/LoadingSpinner';
import ScreenHeader from '../../components/ScreenHeader';
import { COLORS, FONTS, RADIUS, SHADOW } from '../../theme';

const ReportDetailScreen = ({ route, navigation }) => {
  const { reportId } = route.params;
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchReport = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getReportByIdApi(reportId);
      setReport(res.data);
    } catch (e) {
      console.error('Error fetching report:', e);
      Alert.alert('Error', e.response?.data?.message || 'Failed to load report.');
      navigation.goBack();
    } finally {
      setLoading(false);
    }
  }, [reportId, navigation]);

  useFocusEffect(
    useCallback(() => {
      fetchReport();
    }, [fetchReport])
  );

  const handleDelete = () => {
    Alert.alert(
      'Delete Report',
      'Are you sure you want to delete this report?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteReportApi(reportId);
              Alert.alert('Success', 'Report deleted successfully.', [
                { text: 'OK', onPress: () => navigation.goBack() },
              ]);
            } catch (e) {
              Alert.alert('Error', e.response?.data?.message || 'Failed to delete report.');
            }
          },
        },
      ]
    );
  };

  if (loading) return <LoadingSpinner message="Loading report..." />;

  if (!report) {
    return (
      <View style={styles.root}>
        <ScreenHeader title="Report" onBack={() => navigation.goBack()} />
        <View style={styles.emptyContainer}>
          <Text style={styles.emptyText}>Report not found</Text>
        </View>
      </View>
    );
  }

  const getReportIcon = (reportType) => {
    const icons = {
      appointments: '📅',
      revenue: '💰',
      doctor_performance: '👨‍⚕️',
    };
    return icons[reportType] || '📄';
  };

  const getReportColor = (reportType) => {
    const colors = {
      appointments: { bg: COLORS.tealFaint, accent: COLORS.tealBright },
      revenue: { bg: '#e6f7f0', accent: COLORS.success },
      doctor_performance: { bg: '#fff7ed', accent: COLORS.warning },
    };
    return colors[reportType] || { bg: COLORS.bgPage, accent: COLORS.textMuted };
  };

  const colors = getReportColor(report.reportType);
  const createdDate = new Date(report.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <View style={styles.root}>
      <ScreenHeader title={report.title} onBack={() => navigation.goBack()} />

      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {/* Header Card */}
        <View style={[styles.headerCard, { backgroundColor: colors.bg, borderLeftColor: colors.accent }]}>
          <View style={[styles.iconBox, { backgroundColor: 'rgba(0,0,0,0.05)' }]}>
            <Text style={styles.reportIcon}>{getReportIcon(report.reportType)}</Text>
          </View>
          <View style={styles.headerInfo}>
            <Text style={styles.reportTitle}>{report.title}</Text>
            <Text style={styles.reportType}>{report.reportType.replace('_', ' ').toUpperCase()}</Text>
            <Text style={styles.reportDate}>{createdDate}</Text>
          </View>
        </View>

        {/* Report Data Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>REPORT DATA</Text>
          <View style={styles.dataContainer}>
            {renderReportData(report.data)}
          </View>
        </View>

        {/* Generated By Section */}
        {report.generatedBy && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>GENERATED BY</Text>
            <View style={styles.generatedByCard}>
              <Text style={styles.adminName}>{report.generatedBy.name || 'Admin'}</Text>
              <Text style={styles.adminEmail}>{report.generatedBy.email}</Text>
            </View>
          </View>
        )}

        {/* Delete Button */}
        <TouchableOpacity
          style={styles.deleteBtn}
          onPress={handleDelete}
          activeOpacity={0.85}
        >
          <Text style={styles.deleteBtnText}>Delete Report</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
};

const formatLabel = (str) => {
  return str
    .replace(/_/g, ' ')
    .replace(/([A-Z])/g, ' $1')
    .replace(/^\s/, '')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
};

const formatValue = (value) => {
  if (typeof value === 'number') {
    return value.toLocaleString();
  }
  if (typeof value === 'boolean') {
    return value ? 'Yes' : 'No';
  }
  if (value === null || value === undefined) {
    return 'N/A';
  }
  return String(value);
};

const renderReportData = (data) => {
  if (!data) {
    return <Text style={{ color: COLORS.textMuted }}>No data available</Text>;
  }

  // If data is an array, render each item
  if (Array.isArray(data)) {
    return data.map((item, idx) => (
      <View key={idx} style={styles.dataSection}>
        {typeof item === 'object' && item !== null ? (
          <>
            <Text style={styles.dataSectionTitle}>Item {idx + 1}</Text>
            {Object.entries(item).map(([key, value]) => (
              <View key={key} style={styles.dataRowInner}>
                <Text style={styles.dataLabel}>{formatLabel(key)}</Text>
                <Text style={styles.dataValue}>{formatValue(value)}</Text>
              </View>
            ))}
          </>
        ) : (
          <Text style={styles.dataValue}>{formatValue(item)}</Text>
        )}
      </View>
    ));
  }

  // If data is an object, render key-value pairs
  if (typeof data === 'object') {
    return Object.entries(data).map(([key, value]) => (
      <View key={key}>
        {typeof value === 'object' && value !== null ? (
          <View style={styles.dataSection}>
            <Text style={styles.dataSectionTitle}>{formatLabel(key)}</Text>
            {Array.isArray(value) ? (
              value.map((item, idx) =>
                typeof item === 'object' ? (
                  <View key={idx} style={styles.nestedObject}>
                    {Object.entries(item).map(([k, v]) => (
                      <View key={k} style={styles.dataRowInner}>
                        <Text style={styles.dataLabel}>{formatLabel(k)}</Text>
                        <Text style={styles.dataValue}>{formatValue(v)}</Text>
                      </View>
                    ))}
                  </View>
                ) : (
                  <Text key={idx} style={[styles.dataValue, { marginBottom: 6 }]}>
                    {formatValue(item)}
                  </Text>
                )
              )
            ) : (
              Object.entries(value).map(([k, v]) => (
                <View key={k} style={styles.dataRowInner}>
                  <Text style={styles.dataLabel}>{formatLabel(k)}</Text>
                  <Text style={styles.dataValue}>{formatValue(v)}</Text>
                </View>
              ))
            )}
          </View>
        ) : (
          <View style={styles.dataRow}>
            <Text style={styles.dataLabel}>{formatLabel(key)}</Text>
            <Text style={styles.dataValue}>{formatValue(value)}</Text>
          </View>
        )}
      </View>
    ));
  }

  return <Text style={styles.dataValue}>{formatValue(data)}</Text>;
};

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bgPage },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },

  headerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    ...SHADOW.card,
  },
  iconBox: {
    width: 56,
    height: 56,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportIcon: { fontSize: 28 },
  headerInfo: { flex: 1 },
  reportTitle: { fontSize: 16, fontWeight: FONTS.bold, color: COLORS.navyDeep },
  reportType: { fontSize: 11, fontWeight: FONTS.semibold, color: COLORS.tealBright, letterSpacing: 0.5, marginTop: 4 },
  reportDate: { fontSize: 12, color: COLORS.textMuted, marginTop: 4 },

  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 10, fontWeight: FONTS.bold, color: COLORS.tealBright, letterSpacing: 2, marginBottom: 12, marginLeft: 4 },

  dataContainer: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 16,
    ...SHADOW.card,
  },
  dataRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  dataSection: {
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  dataSectionTitle: {
    fontSize: 13,
    fontWeight: FONTS.semibold,
    color: COLORS.tealStrong,
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.tealPale,
  },
  dataRowInner: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(13, 127, 111, 0.03)',
    borderRadius: RADIUS.sm,
    marginBottom: 8,
  },
  nestedObject: {
    marginBottom: 12,
    paddingLeft: 8,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.tealLight,
  },
  dataLabel: { fontSize: 12, fontWeight: FONTS.semibold, color: COLORS.tealBright, marginBottom: 4 },
  dataValue: { fontSize: 14, fontWeight: FONTS.regular, color: COLORS.navyDeep },

  generatedByCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 16,
    ...SHADOW.card,
  },
  adminName: { fontSize: 15, fontWeight: FONTS.bold, color: COLORS.navyDeep, marginBottom: 4 },
  adminEmail: { fontSize: 13, color: COLORS.textMuted },

  deleteBtn: {
    backgroundColor: '#FF5252',
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    ...SHADOW.btn,
  },
  deleteBtnText: { fontSize: 15, fontWeight: FONTS.semibold, color: COLORS.white },

  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyText: { fontSize: 16, color: COLORS.textMuted },
});

export default ReportDetailScreen;
